import groovy.sql.Sql
import org.h2.Driver

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class App {

    static void main(String[] args) {
        //def sql = Sql.newInstance("jdbc:h2:mem:chinook;MODE=DB2", "org.h2.Driver")
        def sql = Sql.newInstance("jdbc:h2:./chinook;MODE=DB2", "org.h2.Driver")

        //sql.execute("Chinook_H2.sql")
        String sqlFilePath = "src/main/resources/Chinook_H2.sql"
        String sqlString = new File(sqlFilePath).text
        sql.execute(sqlString)

        // Execute a normal sql query on this table...
        sql.eachRow('select * from "Track"') { row ->
            println row
        }
    }
}
