import groovy.sql.Sql
import org.h2.Driver

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class App {

    static void main(String[] args) {
        //def sql = Sql.newInstance("jdbc:h2:mem:chinook;MODE=DB2", "org.h2.Driver")
        def sql = Sql.newInstance("jdbc:h2:./chinook;MODE=DB2", "org.h2.Driver")

        String currentDir = new File(".").getCanonicalPath()
        println currentDir

        println "Creating tables"
        String createSQL = new File("src/main/resources/create.sql").text
        sql.execute(createSQL)

        println "Populating tables"
        String populateSQL = new File("src/main/resources/populate.sql").text
        sql.execute(populateSQL)

        // Execute a normal sql query on this table...
        sql.eachRow('select * from "Track"') { row ->
            println row
        }
    }
}
