import groovy.sql.Sql

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */

class App {

    static void main(String[] args) {
        //def sql = Sql.newInstance("jdbc:h2:mem:chinook;MODE=DB2", "org.h2.Driver")
        def sql = Sql.newInstance("jdbc:h2:./db/chinook;MODE=DB2", "sa", "", "org.h2.Driver")

        String currentDir = new File(".").getCanonicalPath()
        println currentDir

        println "Creating tables"
        String createSQL = new File("src/main/resources/create.sql").text
        sql.execute(createSQL)

        println "Populating tables"
        String populateSQL = new File("src/main/resources/populate.sql").text
        sql.execute(populateSQL)

        // Execute a normal sql query on this table...
        sql.eachRow('select * from "Track"') { row ->
            println row
        }
        println "Backup"
        new org.h2.tools.Script().process("jdbc:h2:./db/chinook;MODE=DB2", "sa", "", "./db/backup.sql", "", "")
    }
}
